### PR TITLE
Change logo and favicon

### PR DESCRIPTION
**Pull request by Jeligit**

### CODE REVIEW

**Comment by SeniorCanard** [comment]
Hi, 
I'd like to contribute. 
Here is my first proposition, a second one will follow in few days.  
logo1

**Comment by Galand-V** [comment]
Hello Everyone, 

I would also would like to suggest my logo  : 

logo cerberus

Feel free to comment and tell me what you think about it.

**Comment by Galand-V** [comment]
Here are 2 other suggestions : 

cerberus_landscape_1
cerberus_landscape_2

**Comment by SeniorCanard** [comment]
Hello, 
as promised, here is my 2nd contribution 
v2

**Comment by bcivel** [comment]
Just in time for the survey ;-)

**Comment by abourdon** [comment]
Thanks for your contribution @Jeligit, @SeniorCanard and @Galand-V. We have clearly more skills in logo design than us ;-)

**Comment by vertigo17** [comment]
@Galand-V , can you upload the source of the logo (svg) into /docs/logo/ ?
Thanks.

**Pull request closed without merging**
