### PR TITLE
Adding step number in testCaseScript and testCaseExecution 

### PR DESCRIPTION
**Pull request by vitoo**
Hello,

i find it more clear to have step numbers like this :

Script : 

image

Execution : 

image

Thanks :)

### CODE REVIEW

**Comment by vertigo17** [comment]
Good idea. Thanks for the proposal.
If we want it to be user friendly we should display sort information in stead of stepId.
If we disply StepId, user could see 1 then 5 then 2 which will make it very confusing.
Can you correct that ?

**Comment by vitoo** [comment]
Not ready yet, in testCaseScript a refresh of step number is missing after the drag and drop re-order

**Comment by vertigo17** [comment]
Hello @vitoo is that PR ready for review/merge ?

**Comment by vitoo** [comment]
Yes, i tested again it seems ok

**Pull request merged**
